Repository nasa/elf2cfetbl, pull requests merged in 2020-07, with the labels that each got.

#46 Fix #45 - null terminates src/dst filenames
  elf2cfetbl.c
Labels: CCB-20200624, IC-20200624, code reviewed

#49 Fix #48, string table identification.
  elf2cfetbl.c
Labels: CCB - Fast Track, IC-20200624, bug

#51 Resolve #50, Add baseline and build number to version.h
  elf2cfetbl.c
  elf2cfetbl_version.h
Labels: CCB - Fast Track, IC-20200624

#47 Integration Candidate: 2020-06-24
  README.md
  elf2cfetbl.c
  elf2cfetbl_version.h
Labels: IC-20200624
