Repository nasa/elf2cfetbl, pull requests merged in 2020-05, with the labels that each got.

#40 Integration Candidate: 2020-04-22
  README.md
  elf2cfetbl.c
Labels: IC-20200422

#38 Fix #37, termination on strncpy
  elf2cfetbl.c
Labels: CCB-20200429, IC-20200429, bug, code reviewed

#39 Fix typos
  ELF_Structures.h
  README.txt
Labels: CCB-20200429, IC-20200429, code reviewed, docs, enhancement

#41 Integration Candidate COMBINED 2020-04-29 and 2020-05-06
  ELF_Structures.h
  README.md
  README.txt
  elf2cfetbl.c
Labels: IC-20200429

#42 Fix #32, Apply standard code style
  ELF_Structures.h
  SampleTblImg.c
  elf2cfetbl.c
Labels: CCB - Fast Track, IC-20200520, enhancement

#44 Integration Candidate: 2020-05-20
  ELF_Structures.h
  README.md
  SampleTblImg.c
  elf2cfetbl.c
Labels: IC-20200520
